// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoSetWallpaper():Promise<void>;

export function ChangeWallpaperNow():Promise<void>;

export function GetAndSetWallpaper(arg1:string):Promise<string>;

export function GetBingWallpapers():Promise<Array<main.BingWallpaper>>;

export function ShowWindow():Promise<void>;
