// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSetWallpaper() {
  return window['go']['main']['App']['AutoSetWallpaper']();
}

export function ChangeWallpaperNow() {
  return window['go']['main']['App']['ChangeWallpaperNow']();
}

export function GetAndSetWallpaper(arg1) {
  return window['go']['main']['App']['GetAndSetWallpaper'](arg1);
}

export function GetBingWallpapers() {
  return window['go']['main']['App']['GetBingWallpapers']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
